spring:
  config:
    activate:
      on-profile: "production"


build:
  version: "2.0"

accounts:
  message: "Welcome, this is my demo project!"
  contactDetails:
    name: "Amit"
    email: "amit@gmail.com"
  onCallSupport:
    -398498983298329