server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true

  config:
    import:
      - "application_qa.yaml"

  profiles:
    active: "loans_qa"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  build:
    version: "1.0"

  loans:
    message: "local information server:"
    contactInfo:
      name: "aman"
      email: "aman2312@gmail.com"
    onCallSupport:
      - "845488478347"
      - "474576736746"